function print_info(idx_nml::IDX_NML)
    println("D:                   ", idx_nml.D)
    println("E:                   ", idx_nml.E)
    println("ET:                  ", idx_nml.ET)
    println("S:                   ", idx_nml.S)
    println("PX:                  ", idx_nml.PX)
    println("PY:                  ", idx_nml.PY)
    println("PZ:                  ", idx_nml.PZ)
    println("BX:                  ", idx_nml.BX)
    println("BY:                  ", idx_nml.BY)
    println("BZ:                  ", idx_nml.BZ)
    println("QR:                  ", idx_nml.QR)
    println("TT:                  ", idx_nml.TT)
    println("PHI:                 ", idx_nml.PHI)
    println("P1:                  ", idx_nml.P1)
    println("P2:                  ", idx_nml.P2)
    println("P3:                  ", idx_nml.P3)
    println("B1:                  ", idx_nml.B1)
    println("B2:                  ", idx_nml.B2)
    println("B3:                  ", idx_nml.B3)
    println("EX:                  ", idx_nml.EX)
    println("EY:                  ", idx_nml.EY)
    println("EZ:                  ", idx_nml.EZ)
    println("JX:                  ", idx_nml.JX)
    println("JY:                  ", idx_nml.JY)
    println("JZ:                  ", idx_nml.JZ)
    println("RPHI:                ", idx_nml.RPHI)
end

function print_info(io_nml::IO_NML)
    println("FORMAT:              ", io_nml.FORMAT)
    println("NTOTAL:              ", io_nml.NTOTAL)
    println("OUT_TIME:            ", io_nml.OUT_TIME)
    println("GUARD_ZONES:         ", io_nml.GUARD_ZONES)
    println("TIME_DERIVS:         ", io_nml.TIME_DERIVS)
    println("METHOD:              ", io_nml.METHOD)
    println("NML_VERSION:         ", io_nml.NML_VERSION)
    println("DO_GENERIC:          ", io_nml.DO_GENERIC)
    println("DO_PIC:              ", io_nml.DO_PIC)
    println("DO_PARTICLES:        ", io_nml.DO_PARTICLES)
end

function print_info(snapshot_nml::SNAPSHOT_NML)
    println("IOFORMAT:            ", snapshot_nml.IOFORMAT)
    println("IOUT:                ", snapshot_nml.IOUT)
    println("TIME:                ", snapshot_nml.TIME)
    println("NTOTAL:              ", snapshot_nml.NTOTAL)
    println("BOX:                 ", snapshot_nml.BOX)
    println("LI:                  ", snapshot_nml.LI)
    println("UI:                  ", snapshot_nml.UI)
    println("NG:                  ", snapshot_nml.NG)
    println("GN:                  ", snapshot_nml.GN)
    println("N:                   ", snapshot_nml.N)
    println("NV:                  ", snapshot_nml.NV)
    println("MV:                  ", snapshot_nml.MV)
    println("NT:                  ", snapshot_nml.NT)
    println("GAMMA:               ", snapshot_nml.GAMMA)
    println("EOS_NAME:            ", snapshot_nml.EOS_NAME)
    println("OPACITY:             ", snapshot_nml.OPACITY)
    println("PERIODIC:            ", snapshot_nml.PERIODIC)
    println("GUARD_ZONES:         ", snapshot_nml.GUARD_ZONES)
    println("TIME_DERIVS:         ", snapshot_nml.TIME_DERIVS)
    println("NO_MANS_LAND:        ", snapshot_nml.NO_MANS_LAND)
    println("OMP_NTHREADS:        ", snapshot_nml.OMP_NTHREADS)
    println("MPI_SIZE:            ", snapshot_nml.MPI_SIZE)
    println("MESH_TYPE:           ", snapshot_nml.MESH_TYPE)
    println("MPI_DIMS:            ", snapshot_nml.MPI_DIMS)
    println("REFINE_RATIO:        ", snapshot_nml.REFINE_RATIO)
    println("ORIGIN:              ", snapshot_nml.ORIGIN)
end

function print_info(nbor_nml::NBOR_NML)
    println("PARENT_ID:           ", nbor_nml.PARENT_ID)
    println("NBOR_IDS:            ", join(nbor_nml.NBOR_IDS, ", "))
end

function print_info(patch_nml::Patch_NML)
    println("ID:                  ", patch_nml.ID)
    println("POSITION:            ", join(patch_nml.POSITION, ", "))
    println("SIZE:                ", join(patch_nml.SIZE, ", "))
    println("LEVEL:               ", patch_nml.LEVEL)
    println("DTIME:               ", patch_nml.DTIME)
    println("ISTEP:               ", patch_nml.ISTEP)
    println("DS:                  ", join(patch_nml.DS, ", "))
    println("NCELL:               ", join(patch_nml.NCELL, ", "))
    println("N:                   ", join(patch_nml.N, ", "))
    println("NW:                  ", patch_nml.NW)
    println("VELOCITY:            ", join(patch_nml.VELOCITY, ", "))
    println("QUALITY:             ", patch_nml.QUALITY)
    println("MESH_TYPE:           ", patch_nml.MESH_TYPE)
    println("KIND:                ", patch_nml.KIND)
    println("ETYPE:               ", patch_nml.ETYPE)
    println("RECORD:              ", patch_nml.RECORD)
    println("RANK:                ", patch_nml.RANK)
    println("IPOS:                ", join(patch_nml.IPOS, ", "))
    println("COST:                ", patch_nml.COST)
    println("CENTRE_NAT:          ", join(patch_nml.CENTRE_NAT, ", "))
    println("LLC_NAT:             ", join(patch_nml.LLC_NAT, ", "))
    println("EROT1:               ", join(patch_nml.EROT1, ", "))
    println("EROT2:               ", join(patch_nml.EROT2, ", "))
    println("EROT3:               ", join(patch_nml.EROT3, ", "))
    println("NBOR_NML:            ")
    print_info(patch_nml.NBOR_NML)
    println("DATA_POS:            ", patch_nml.DATA_POS)
    println("DATA_FILE:           ", patch_nml.DATA_FILE)
end



function print_info(particle_nml::Particles_NML)
    println("ID:                  ", particle_nml.ID)
    println("Number of Species:   ", particle_nml.N_SPECIES)
    println("Do Particles:        ", particle_nml.DO_PARTICLES)
    println("#Particle Fields:    ", particle_nml.NV_PARTICLE_FIELDS)
    println("Is Electron:         ", join(particle_nml.IS_ELECTRON, ", "))
    println("Mass:                ", join(particle_nml.MASS, ", "))
    println("Charge:              ", join(particle_nml.CHARGE, ", "))
    println("M:                   ", join(particle_nml.M, ", "))
    println("Data Position:       ", particle_nml.DATA_POS)
    println("Data File:           ", particle_nml.DATA_FILE)
end

function print_info(metadata::Snapshot_metadata)
    println("IO:                  ")
    print_info(metadata.IO)
    println("\nSNAPSHOT:          ")
    print_info(metadata.SNAPSHOT)
    println("\nIDX:               ")
    print_info(metadata.IDX)
    println("\nScaling:               ")
    print_info(metadata.SCALING)
    println("\n      NV_MHD:      ", metadata.NV_MHD)
    println("\nNumber of PATCHES: ", metadata.n_patches)
    println("\n Folder:           ", metadata.folder)
    
    if metadata.DO_PIC
    println("        PIC PATCHES: ", metadata.n_pic_patches)
    println("        NV_PIC:      ", metadata.NV_PIC)
        if metadata.DO_PARTICLES
            println("\nParticle Folder:   ", metadata.PARTICLE_FOLDER)
        end
    end
end


"""
Print the contents of a `ScalingParams` struct in a formatted way.
"""
function print_info(s::SCALING_NML)
    println("N_P_REAL:            ", s.N_P_REAL)
    println("L_REAL:              ", s.L_REAL)
    println("TEMP_REAL:           ", s.TEMP_REAL)
    println("B_REAL:              ", s.B_REAL)
    println("MU_REAL:             ", s.MU_REAL)
    println("ELECTRON_TEMP_REAL:  ", s.ELECTRON_TEMP_REAL)
    println("ION_TEMP_REAL:       ", s.ION_TEMP_REAL)
    println("L scaling:           ", s.L)
    println("D scaling:           ", s.D)
    println("T scaling:           ", s.T)
    println("Q_E_SCALE:           ", s.Q_E_SCALE)
    println("M_E_SCALE:           ", s.M_E_SCALE)
    println("MU_0_SCALE:          ", s.MU_0_SCALE)
    println("EPS_0_SCALE:         ", s.EPS_0_SCALE)
    println("SYSTEM:              ", s.SYSTEM)
    println("PER_CELL:            ", s.PER_CELL)
    println("SPECIES:             ", s.SPECIES)
    println("DS:                  ", s.DS)
end
